 version: "3"
 services:
  nginx:
    image: nginx:stable-alpine
    ports:
     - 5000:80
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # mount nginx config
 
  node-app:
    build: . # use the Dockerfile in the current directory
    environment:
      - PORT=5050 # container
    