version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 5000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-app:
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=5050
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - DOMAIN=${DOMAIN}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    deploy:
      restart_policy:
        condition: on-failure